version: '3'

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M Y S Q L                                  #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    ports:
        - 3306:3306
    volumes:
        - ./datas:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks: 
      - myown_network

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-mysql8
    restart: unless-stopped
    ports:
      - 81:80
    links:
        - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    volumes:
      - ./datas/sessions:/sessions
    networks: 
      - myown_network

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                             N E T W O R K                                #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------# 
networks:
  myown_network:
    driver: bridge